# permissions for end users to view glsstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glsstorage-viewer-role
rules:
- apiGroups:
  - gls.my.domain
  resources:
  - glsstorages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gls.my.domain
  resources:
  - glsstorages/status
  verbs:
  - get
